version: "3"

services:
  api:
    image: ghcr.io/hydrophobefireman/minimal-system-status:release
    network_mode: host
    restart: unless-stopped
    environment:
      - PORT=12000
    volumes:
      - /mnt/hdd:/hdd:ro
